#!/usr/bin/env bash
# Deploys site/ to S3 under the "site/" prefix, with a config.js generated
# from Terraform's outputs. Run after an apply, or any time only the frontend
# has changed.
#
# site/ is copied into build/site/ and deployed from there, with a generated
# config.js written over the committed one. The copy in site/ keeps its
# placeholder values and never shows up as a local change carrying your
# Cognito ids.
#
# Usage: scripts/deploy_site.sh
set -euo pipefail
cd "$(dirname "$0")/.."

set -a
source .env   # see env.example
set +a

tf() { python scripts/tf.py output -raw "$1"; }

DOMAIN=$(tf site_domain)
COGNITO_DOMAIN=$(tf cognito_hosted_ui_domain)
COGNITO_CLIENT_ID=$(tf cognito_client_id)
DISTRIBUTION_ID=$(tf cloudfront_distribution_id)

rm -rf build/site
mkdir -p build/site
# The local preview artefacts and the folder's own README are not deployed.
tar -cf - --exclude=manifest.json --exclude=sample-photos --exclude=README.md -C site . | tar -xf - -C build/site

cat > build/site/config.js << EOF
// GENERATED by scripts/deploy_site.sh -- do not hand-edit, it will be overwritten.
export const MANIFEST_URL = "/photos/manifest.json";
export const API_BASE = "/api";
export const COGNITO_DOMAIN = "${COGNITO_DOMAIN}";
export const COGNITO_CLIENT_ID = "${COGNITO_CLIENT_ID}";
export const REDIRECT_URI = "https://${DOMAIN}/auth/callback";
EOF

aws s3 sync build/site/ "s3://${S3_BUCKET}/site/" \
  --profile "${AWS_PROFILE}" --region "${AWS_REGION}" --delete

aws cloudfront create-invalidation \
  --distribution-id "${DISTRIBUTION_ID}" --paths "/*" \
  --profile "${AWS_PROFILE}"

echo "Deployed to https://${DOMAIN}/"
