#!/usr/bin/env python3
"""Deploy site/ to S3 under the "site/" prefix, with a config.js generated
from Terraform's outputs, then invalidate CloudFront.

The generated config.js is written to build/ and uploaded from there. The
copy in site/ keeps its placeholder values.

Usage: python scripts/deploy_site.py
"""

import shutil
import subprocess
import sys
from pathlib import Path

from dotenv import dotenv_values

ROOT = Path(__file__).resolve().parent.parent
ENV_PATH = ROOT / ".env"
BUILD_DIR = ROOT / "build"

REQUIRED = ["S3_BUCKET", "AWS_REGION", "AWS_PROFILE"]

OUTPUTS = [
    "site_domain",
    "cognito_hosted_ui_domain",
    "cognito_client_id",
    "cloudfront_distribution_id",
]

CONFIG_TEMPLATE = """\
// GENERATED by scripts/deploy_site.py -- do not hand-edit, it will be overwritten.
export const MANIFEST_URL = "/photos/manifest.json";
export const API_BASE = "/api";
export const COGNITO_DOMAIN = "{cognito_hosted_ui_domain}";
export const COGNITO_CLIENT_ID = "{cognito_client_id}";
export const REDIRECT_URI = "https://{site_domain}/auth/callback";
"""


def fail(message):
    print("deploy_site: " + message, file=sys.stderr)
    raise SystemExit(1)


def load_env():
    if not ENV_PATH.exists():
        fail("no .env in the repo root -- copy env.example to .env")
    env = {k: v for k, v in dotenv_values(ENV_PATH).items() if v}
    missing = [k for k in REQUIRED if k not in env]
    if missing:
        fail(".env is missing " + ", ".join(missing))
    return env


def aws_path():
    found = shutil.which("aws")
    if not found:
        fail("the aws CLI is not on PATH")
    return found


def tf_output(name):
    result = subprocess.run(
        [sys.executable, str(ROOT / "scripts" / "tf.py"), "output", "-raw", name],
        cwd=ROOT,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        sys.stderr.write(result.stderr)
        fail("terraform output %s failed -- has the stack been applied?" % name)
    value = result.stdout.strip()
    if not value:
        fail("terraform output %s is empty" % name)
    return value


def run(argv):
    print("$ " + " ".join(argv))
    result = subprocess.run(argv, cwd=ROOT)
    if result.returncode != 0:
        raise SystemExit(result.returncode)


def main():
    env = load_env()
    aws = aws_path()

    outputs = {name: tf_output(name) for name in OUTPUTS}

    BUILD_DIR.mkdir(exist_ok=True)
    config = BUILD_DIR / "config.js"
    config.write_text(CONFIG_TEMPLATE.format(**outputs), encoding="utf-8")
    print("wrote " + str(config.relative_to(ROOT)))

    profile = ["--profile", env["AWS_PROFILE"]]
    region = ["--region", env["AWS_REGION"]]
    bucket = env["S3_BUCKET"]

    run(
        [aws, "s3", "sync", "site/", "s3://%s/site/" % bucket]
        + profile
        + region
        + [
            "--exclude", "manifest.json",
            "--exclude", "config.js",
            "--exclude", "README.md",
            "--delete",
        ]
    )

    run(
        [aws, "s3", "cp", str(config), "s3://%s/site/config.js" % bucket]
        + profile
        + region
        + ["--content-type", "application/javascript"]
    )

    run(
        [aws, "cloudfront", "create-invalidation",
         "--distribution-id", outputs["cloudfront_distribution_id"],
         "--paths", "/*"]
        + profile
    )

    print("Deployed to https://%s/" % outputs["site_domain"])


if __name__ == "__main__":
    main()
